{% set name = "PyMySQL" %}
{% set version = "0.10.0" %}
{% set sha256 = "e14070bc84e050e0f80bf6063e31d276f03a0bb4d46b9eca2854566c4ae19837" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pymysql

about:
  home: http://github.com/PyMySQL/PyMySQL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python MySQL Driver
  description: |
    This package contains a pure-Python MySQL client library. The goal of
    PyMySQL is to be a drop-in replacement for MySQLdb and work on CPython,
    PyPy and IronPython.
  doc_url: http://pymysql.readthedocs.io/
  dev_url: https://github.com/PyMySQL/PyMySQL

extra:
  recipe-maintainers:
    - djsutherland
