{% set name = "PyMySQL" %}
{% set version = "1.1.0" %}
{% set sha256 = "4f13a7df8bf36a51e81dd9f3605fede45a4878fe02f9236349fd82a3f0612f96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - pymysql

about:
  home: http://github.com/PyMySQL/PyMySQL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python MySQL Driver
  description: |
    This package contains a pure-Python MySQL client library. The goal of
    PyMySQL is to be a drop-in replacement for MySQLdb and work on CPython,
    PyPy and IronPython.
  doc_url: http://pymysql.readthedocs.io/
  dev_url: https://github.com/PyMySQL/PyMySQL

extra:
  recipe-maintainers:
    - djsutherland
    - synapticarbors
