{% set name = "PyMySQL" %}
{% set version = "1.0.3" %}
{% set sha256 = "3dda943ef3694068a75d69d071755dbecacee1adf9a1fc5b206830d2b67d25e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - pymysql

about:
  home: http://github.com/PyMySQL/PyMySQL
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure Python MySQL Driver
  description: |
    This package contains a pure-Python MySQL client library. The goal of
    PyMySQL is to be a drop-in replacement for MySQLdb and work on CPython,
    PyPy and IronPython.
  doc_url: http://pymysql.readthedocs.io/
  dev_url: https://github.com/PyMySQL/PyMySQL

extra:
  recipe-maintainers:
    - djsutherland
    - synapticarbors
