travis:
  secure:
    BINSTAR_TOKEN: duGQkje+TzRN1Dpp2t+cXm0aM1f+P087FttGEK1WXaFk3V7LXXtviOagfa4pjOgeBhcTpMDFdNGFNNXeScIdyrtvtNCWp7Dh1xYQeLF9h89zqmUGSaWYjvaEZhlygyKa2G0DdNh/qV4vzdQJI8FW24SNcsaGUoUFLfi3llvfSi5Oa3TmJMP1uc+u2oPkUBmJV0Qol3Pf0tyLYfFrUf2F+Rt6a1PyrXsBcrw0qzrGYrnY/R33CMAtdRAjvStNVQA1dDiOTkCmxQBYZOhmEj2J2CpMLtSgpvbp9G904QM9arNstLSLeoRnQxmprY842Vdsrj3i/UEGZp79YxM4K5SXdMYv1Lz+egmWRva65wbg2Rv+zD656GBpujIvQOzpHc9/tBnqysZYPBocHfsEOPcE0Tmr0QDGvxmp8+RF+Rqgo8uMlwNXmKRbprt7TohRwPPiFi6GIXK6qrUB8E4kpg56VndUGOj+yQOFGL8MQfuxxWhZbfFEbXLtmMkCFYK9rCeIXEtg4UE7snlnfaEKowqNIIskSrPRqlAz/Ai16MAsTissiQpZ1kZUMlFG5HC2aDtw8IGQS4Akryh0oepTEbEBDebJYbuxh96fj+fOU1iLldazwezH+mXjn+wPaigka52SRH+zjuESmXZo7+CPjckfLAzHfv3ABGWHihKehnNJDqI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
